version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.3.3

    working_directory: ~/repo

    steps:
      - checkout

      - run: bundle install

      - run: bundle exec appraisal install

      - run:
          name: Run test suite with Minitest
          command: |
            bundle exec appraisal rake test_minitest

      - run:
          name: Run test suite with Rspec
          command: |
            bundle exec appraisal rake test_rspec
